CREATE TABLE IF NOT EXISTS city (
    id BIGSERIAL PRIMARY KEY,
    pptBr INT CONSTRAINT pptBr_range_chk CHECK (pptBr BETWEEN 11000 AND 40000) UNIQUE NOT NULL,
    name VARCHAR(30) NOT NULL CHECK (LENGTH(name) BETWEEN 2 AND 30),
    population INT NOT NULL CHECK (population > 0)
);
